name: "Deploy App"

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          #Set Java Version
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with maven
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: studentdb-backend.jar
          path: target/studentdb-backend.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: studentdb-backend.jar
          path: target

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          #Set dockerhub username
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          #Set dockerhub project (replace "bartfastiel/deploy-to-aws-with-github-actions")
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deploy-to-aws-with-github-action:latest
          context: .
  
  deploy:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Restart docker container
        uses: appleboy/ssh-action@master
        with:
          #Set hostname of your AWS EC2 instance
          host: ec2-12-345-67-89.eu-central-1.compute.amazonaws.com
          #Set App Name ("myapp" - "tango")
          username: antimon
          password: ${{ secrets.SSH_PASSWORD }}
          #Set App Name ("myapp" - "tango")
          #Set dockerhub project (replace "bartfastiel/deploy-to-aws-with-github-actions")
          script: |
            docker stop antimon
            docker rm antimon
            docker run --pull=always --name antimon --publish 80:8080 --restart always --detach sergejneuefische/deploy-to-aws-with-github-action:latest
            sleep 15s
            docker logs antimon
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Set URL of your AWS EC2 instance
          url: http://ec2-12-345-67-89.eu-central-1.compute.amazonaws.com
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
